export { default as HospitalProfile } from "./HospitalProfile";
export { default as BasicInformation } from "./BasicInformation";
export { default as HospitalCapacity } from "./HospitalCapacity";
export { default as Accreditations } from "./Accreditations";
export { default as Certifications } from "./Certifications";
export { default as DepartmentManagement } from "./DepartmentManagement";
export { default as SystemConfiguration } from "./SystemConfiguration";
export { default as MasterDataManagement } from "./MasterDataManagement";
export { default as UserRoleManagement } from "./UserRoleManagement";
export { default as InterdepartmentalCommunication } from "./InterdepartmentalCommunication";
export * from "./types";
